-- Agregar los campos a la tabla USER_ENTITY 
INSERT INTO USER_ENTITY (id, name, email, password, created, modified, last_Login, usuario_activo)
VALUES
  (RANDOM_UUID(), 'John Smith', 'john.smith@gmail.com', 'P@ssw0rd1', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true),
  (RANDOM_UUID(), 'Emily Johnson', 'emily.johnson@hotmail.com', 'P@ssw0rd2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true),
  (RANDOM_UUID(), 'Michael Davis', 'michael.davis@gmail.com', 'P@ssw0rd3', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true),
  (RANDOM_UUID(), 'Sarah Wilson', 'sarah.wilson@hotmail.com', 'P@ssw0rd4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true);

-- Agregar los campos a la tabla PHONE_ENTITY
INSERT INTO PHONE_ENTITY (id, number, citycode, contrycode, USER_ENTITY_ID, created, modified, last_Login)
VALUES
  (RANDOM_UUID(), '5551234567', '555', '1', (SELECT id FROM USER_ENTITY WHERE email = 'john.smith@gmail.com'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (RANDOM_UUID(), '5559876543', '555', '1', (SELECT id FROM USER_ENTITY WHERE email = 'john.smith@gmail.com'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (RANDOM_UUID(), '5555555555', '555', '1', (SELECT id FROM USER_ENTITY WHERE email = 'john.smith@gmail.com'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (RANDOM_UUID(), '5551111111', '555', '1', (SELECT id FROM USER_ENTITY WHERE email = 'emily.johnson@hotmail.com'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (RANDOM_UUID(), '5552222222', '555', '1', (SELECT id FROM USER_ENTITY WHERE email = 'emily.johnson@hotmail.com'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (RANDOM_UUID(), '5553333333', '555', '1', (SELECT id FROM USER_ENTITY WHERE email = 'emily.johnson@hotmail.com'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (RANDOM_UUID(), '5554444444', '555', '1', (SELECT id FROM USER_ENTITY WHERE email = 'michael.davis@gmail.com'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (RANDOM_UUID(), '5555555555', '555', '1', (SELECT id FROM USER_ENTITY WHERE email = 'michael.davis@gmail.com'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (RANDOM_UUID(), '5556666666', '555', '1', (SELECT id FROM USER_ENTITY WHERE email = 'michael.davis@gmail.com'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (RANDOM_UUID(), '12345678', '1234', '56', (SELECT id FROM USER_ENTITY WHERE email = 'sarah.wilson@hotmail.com'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (RANDOM_UUID(), '98765432', '9876', '56', (SELECT id FROM USER_ENTITY WHERE email = 'sarah.wilson@hotmail.com'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (RANDOM_UUID(), '87654321', '8765', '56', (SELECT id FROM USER_ENTITY WHERE email = 'sarah.wilson@hotmail.com'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
